### PR TITLE
Introduce display' allowing custom appName

### PR DESCRIPTION
**Pull request by gkleen**
Some notification daemons (such as [dunst](https://github.com/knopwob/dunst)) display the application name set during `notify_init`.

This PR enriches the haskell-API to allow setting it to an appropriate value.

### CODE REVIEW

**Comment by supki** [comment]
(Sorry I've taken so long to reply!)

It's a worthwhile addition, but I don't agree with the implementation.

Instead of adding another variant of `display` (and `close`), I suggest making application name a part of `Mod` (and `Notification`). This way, the description of a notification is separated from the action of displaying it, which I think is a better design.

WDYT?

**Comment by pngwjpgh** [comment]
It would certainly be nicer to have `appName` be part of `Notification`.

It seems to me that all we´d have to do is enrich `Notification` by a `String` (making it a (record style?) `data`-type instead of a `newtype`) and change `act` to use our new record projection instead of `unNotification`?

I´ll try to whip something up in 4 hours or so…

**Comment by pngwjpgh** [comment]
I´m having trouble extending `Notification` to carry an additional `String`.

The structure of `Mod` admits a function `String -> Mod Notification` with the required semantics only if we carry the `String` in `Mod` itself (the monoid-structures of `NotifyNotification` and `String` need to be independent) – that just doesn´t seem _pretty_ to me :-/

If we move `Last` from `Mod` to `Notification` itself we could make `Notification` itself a monoid and get the desired behaviour.

**Comment by supki** [comment]
Well, it makes sense to track application name and `NotifyNotification` separately, as they are independent.

**Comment by pngwjpgh** [comment]
But what would the signature of `close` be if we track the app name in `Mod`?

**Comment by pngwjpgh** [comment]
I hacked something together that I think might work.

I ended up having `Notification` carry the application name and using the `IO`-Operation to set it

**Comment by supki** [comment]
I had something slightly different in mind (#3). Haven't tested yet, but it avoids an unnecessary `notify_init` call. I'll try to merge something in the next few days. (Sorry for the delay on this!)

**Pull request closed without merging**
